SELECT USER
FROM DUAL;
--==>> HR

--■■■ 팀별 실습 과제 ■■■--

-- HR 샘플 스키마 ERD 를 이용한 테이블 재구성~!!!

-- 팀별로... HR 스키마에 있는 기본 테이블 (7개)
-- COUNTRIES / DEPARTMENTS /  EMPLOYEES / JOBS / JOB_HISTORY / LOCATIONS / REGIONS
-- 을 똑~~~~~~같이 새로 구성한다.

-- 단, 생성하는 테이블의 이름은 『테이블명+팀번호』
-- ex) 1팀의 경우...
-- COUNTRIES01 / DEPARTMENTS01 /  EMPLOYEES01 / JOBS01 / JOB_HISTORY01 / LOCATIONS01 / REGIONS01
-- .... 
-- 과 같이 구성한다.

-- 1. 기존 테이블의 정보 수집
-- 2. 테이블 생성(컬럼 이름, 자료형, DEFAULT 표현식, NOT NULL 등...)
--    제약조건 설정(PK, UK, FK, CK, ...NN)
-- 3. 작성 후 데이터 입력
-- 4. 제출 항목
--    20210909_02_hr_팀별실습과제_1조.sql 
--    후기_1조.txt (모든 팀원들의 후기)

SELECT *
FROM TAB;


-- <진행상황(순서)>

-- 1. 생성CREATE :  REGIONS01 / COUNTRIES01 / LOCATIONS01 / JOBS01 / DEPARTMENTS01 /  EMPLOYEES01  / JOB_HISTORY01  
--                                                수지      범석         진령            효빈           윤서        
--                  완             완             완        완           완              완             완

-- 2. 커멘트 :  REGIONS01 / COUNTRIES01 / LOCATIONS01 / JOBS01 / DEPARTMENTS01 /  EMPLOYEES01  / JOB_HISTORY01  
--              커멘트없음       완            완          완           완              완              완


-- 3. 참조 키 제거 : 생성 시... 만들었던 FK 제거

-- 4. 데이터 입력 :  REGIONS01 / COUNTRIES01 / LOCATIONS01 / JOBS01 / DEPARTMENTS01 /  EMPLOYEES01  / JOB_HISTORY01  
--    데이터 수         5건          25건         23건       19건        27건           107건           10건
--                      윤서         효빈         수지       범석        진령          중호             윤서                   

-- 5. 참조 키 추가 지정 : 데이터 입력 후 제거했던 FK 다시 지정




===============================================
--테이블 생성
===============================================


-- 기존 REGIONS 테이블 구조 확인
DESC REGIONS;
/*
이름          널?       유형           
----------- -------- ------------ 
REGION_ID   NOT NULL NUMBER       
REGION_NAME          VARCHAR2(25) 
*/

-- 기존 REGIONS 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='REGIONS';
/*
HR	REGION_ID_NN	REGIONS	C	REGION_ID	"REGION_ID" IS NOT NULL	
HR	REG_ID_PK	    REGIONS	P	REGION_ID		
*/

-- REGIONS01 테이블 생성
CREATE TABLE REGIONS01
( REGION_ID NUMBER CONSTRAINT REGION01_ID_NN NOT NULL
, REGION_NAME VARCHAR2(25) 
, CONSTRAINT REG01_ID_PK PRIMARY KEY(REGION_ID)
);
--==>> Table REGIONS01이(가) 생성되었습니다.

-- 생성 후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='REGIONS01';
/*
HR	REGION01_ID_NN	REGIONS01	C	REGION_ID	"REGION_ID" IS NOT NULL	
HR	REG01_ID_PK	    REGIONS01	P	REGION_ID			
*/

------------------------------------------------------------------------

-- 기존 COUNTRIES 테이블 구조 확인
DESC COUNTRIES;
/*
이름           널?       유형           
------------ -------- ------------ 
COUNTRY_ID   NOT NULL CHAR(2)      
COUNTRY_NAME          VARCHAR2(40) 
REGION_ID             NUMBER  
*/

-- 기존 COUNTRIES 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='COUNTRIES';
/*
HR	COUNTRY_ID_NN	COUNTRIES	C	COUNTRY_ID	"COUNTRY_ID" IS NOT NULL	
HR	COUNTRY_C_ID_PK	COUNTRIES	P	COUNTRY_ID		
HR	COUNTR_REG_FK	COUNTRIES	R	REGION_ID		                    NO ACTION
*/


-- COUNTRIES01 테이블 생성
CREATE TABLE COUNTRIES01
( COUNTRY_ID    CHAR(2) CONSTRAINT COUNTRY01_ID_NN NOT NULL
, COUNTRY_NAME  VARCHAR2(40)
, REGION_ID     NUMBER
, CONSTRAINT COUNTRY01_C_ID_PK PRIMARY KEY(COUNTRY_ID)
, CONSTRAINT COUNTR01_REG_FK FOREIGN KEY(REGION_ID)
              REFERENCES REGIONS01(REGION_ID) 
);
--==>> Table COUNTRIES01이(가) 생성되었습니다.

-- 생성 후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='COUNTRIES01';
/*
HR	COUNTRY01_ID_NN	    COUNTRIES01	C	COUNTRY_ID	"COUNTRY_ID" IS NOT NULL	
HR	COUNTRY01_C_ID_PK	COUNTRIES01	P	COUNTRY_ID		
HR	COUNTR01_REG_FK	    COUNTRIES01	R	REGION_ID		                        NO ACTION
*/


------------------------------------------------------------------------

-- 기존 LOCATIONS 테이블 구조 확인
DESC LOCATIONS;
/*
이름             널?       유형           
-------------- -------- ------------ 
LOCATION_ID    NOT NULL NUMBER(4)    
STREET_ADDRESS          VARCHAR2(40) 
POSTAL_CODE             VARCHAR2(12) 
CITY           NOT NULL VARCHAR2(30) 
STATE_PROVINCE          VARCHAR2(25) 
COUNTRY_ID              CHAR(2)   
*/

-- 기존 LOCATIONS 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='LOCATIONS';
/*
HR	LOC_CITY_NN	LOCATIONS	C	CITY	    "CITY" IS NOT NULL	
HR	LOC_ID_PK	LOCATIONS	P	LOCATION_ID		
HR	LOC_C_ID_FK	LOCATIONS	R	COUNTRY_ID		                NO ACTION
*/

-- LOCATIONS01 테이블생성
CREATE TABLE LOCATIONS01
( LOCATION_ID       NUMBER(4)
, STREET_ADDRESS    VARCHAR2(40)
, POSTAL_CODE       VARCHAR2(12)
, CITY              VARCHAR2(30) CONSTRAINT LOC01_CITY_NN NOT NULL
, STATE_PROVINCE    VARCHAR2(25) 
, COUNTRY_ID        CHAR(2) 
, CONSTRAINT LOC01_ID_PK PRIMARY KEY(LOCATION_ID)
, CONSTRAINT LOC01_C_ID_FK FOREIGN KEY(COUNTRY_ID)
             REFERENCES COUNTRIES01(COUNTRY_ID)
);
--==>> Table LOCATIONS01이(가) 생성되었습니다.

-- 생성 후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='LOCATIONS01';
/*
HR	LOC01_CITY_NN	LOCATIONS01	C	CITY	    "CITY" IS NOT NULL	
HR	LOC01_ID_PK	    LOCATIONS01	P	LOCATION_ID		
HR	LOC01_C_ID_FK	LOCATIONS01	R	COUNTRY_ID		                NO ACTION
*/

------------------------------------------------------------------------

-- 기존 JOBS 테이블 구조 확인
DESC JOBS;
/*
이름         널?       유형           
---------- -------- ------------ 
JOB_ID     NOT NULL VARCHAR2(10) 
JOB_TITLE  NOT NULL VARCHAR2(35) 
MIN_SALARY          NUMBER(6)    
MAX_SALARY          NUMBER(6)  
*/

-- 기존 JOBS 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='JOBS';
/*
HR	JOB_TITLE_NN	JOBS	C	JOB_TITLE	"JOB_TITLE" IS NOT NULL	
HR	JOB_ID_PK	    JOBS	P	JOB_ID		
*/

-- JOBS01 테이블 생성
CREATE TABLE JOBS01
(   JOB_ID      VARCHAR2(10) 
,   JOB_TITLE   VARCHAR2(35)  CONSTRAINT JOB01_TITLE_NN NOT NULL
,   MIN_SALARY  NUMBER(6)    
,   MAX_SALARY  NUMBER(6)
    -- 제약조건
,   CONSTRAINT JOB01_ID_PK PRIMARY KEY(JOB_ID)
);
-- PRIMARY KEY → JOB_ID
-- JOB_TITLE → NOT NULL
--==>> Table JOBS01이(가) 생성되었습니다.


-- 생성 후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='JOBS01';
/*
HR	JOB01_TITLE_NN	JOBS01	C	JOB_TITLE	"JOB_TITLE" IS NOT NULL	
HR	JOB01_ID_PK	JOBS01	    P	JOB_ID				
*/


------------------------------------------------------------------------

-- 기존 DEPARTMENTS 테이블 구조 확인
DESC DEPARTMENTS;
/*
이름              널?       유형           
--------------- -------- ------------ 
DEPARTMENT_ID   NOT NULL NUMBER(4)    
DEPARTMENT_NAME NOT NULL VARCHAR2(30) 
MANAGER_ID               NUMBER(6)    
LOCATION_ID              NUMBER(4)    
*/

-- 기존 DEPARTMENTS 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='DEPARTMENTS';
/*
HR	DEPT_NAME_NN	DEPARTMENTS	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK	    DEPARTMENTS	P	DEPARTMENT_ID		
HR	DEPT_LOC_FK	    DEPARTMENTS	R	LOCATION_ID		                                NO ACTION
HR	DEPT_MGR_FK	    DEPARTMENTS	R	MANAGER_ID		                                NO ACTION
*/

-- DEPARTMENTS01 테이블 생성
CREATE TABLE DEPARTMENTS01
( DEPARTMENT_ID    NUMBER(4)
, DEPARTMENT_NAME  VARCHAR2(30) CONSTRAINT DEPT01_NAME_NN NOT NULL
, MANAGER_ID       NUMBER(6)
, LOCATION_ID      NUMBER(4)
, CONSTRAINT DEPT01_ID_PK PRIMARY KEY(DEPARTMENT_ID)
, CONSTRAINT DEPT01_LOC_FK FOREIGN KEY(LOCATION_ID)
             REFERENCES LOCATIONS01(LOCATION_ID)
);
--==>> Table DEPARTMENTS01이(가) 생성되었습니다.

-- 생성후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='DEPARTMENTS01';
/*
HR	DEPT_NAME_NN01	DEPARTMENTS01	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT_ID_PK01	DEPARTMENTS01	P	DEPARTMENT_ID		
HR	DEPT_LOC_FK01	DEPARTMENTS01	R	LOCATION_ID		                                NO ACTION
*/

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'DEPARTMENTS';
/*
HR	DEPT_MGR_FK	R	DEPARTMENTS		HR	EMP_EMP_ID_PK	NO ACTION	ENABLED	NOT DEFERRABLE	IMMEDIATE	VALIDATED	USER NAME			14/05/29				
*/


-- DEPARTMENTS01, EMPLOYEES01  테이블 생성 후 추가 지정
ALTER TABLE DEPARTMENTS01
ADD CONSTRAINT DEPT01_MGR_FK FOREIGN KEY(MANAGER_ID)
               REFERENCES EMPLOYEES01(EMPLOYEE_ID);
--==>> Table DEPARTMENTS01이(가) 변경되었습니다.


-- 제약조건 추가 후 다시 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='DEPARTMENTS01';
/*
HR	DEPT01_NAME_NN	DEPARTMENTS01	C	DEPARTMENT_NAME	"DEPARTMENT_NAME" IS NOT NULL	
HR	DEPT01_ID_PK	DEPARTMENTS01	P	DEPARTMENT_ID		
HR	DEPT01_LOC_FK	DEPARTMENTS01	R	LOCATION_ID		                                NO ACTION
HR	DEPT01_MGR_FK	DEPARTMENTS01	R	MANAGER_ID		                                NO ACTION
*/


------------------------------------------------------------------------

-- 기존 EMPLOYEES 테이블 구조 확인
DESC EMPLOYEES;
/*
이름             널?       유형           
-------------- -------- ------------ 
EMPLOYEE_ID    NOT NULL NUMBER(6)    
FIRST_NAME              VARCHAR2(20) 
LAST_NAME      NOT NULL VARCHAR2(25) 
EMAIL          NOT NULL VARCHAR2(25) 
PHONE_NUMBER            VARCHAR2(20) 
HIRE_DATE      NOT NULL DATE         
JOB_ID         NOT NULL VARCHAR2(10) 
SALARY                  NUMBER(8,2)  
COMMISSION_PCT          NUMBER(2,2)  
MANAGER_ID              NUMBER(6)    
DEPARTMENT_ID           NUMBER(4)   
*/

-- 기존 EMPLOYEES 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='EMPLOYEES';
/*
HR	EMP_LAST_NAME_NN	EMPLOYEES	C	LAST_NAME	"LAST_NAME" IS NOT NULL	
HR	EMP_EMAIL_NN	    EMPLOYEES	C	EMAIL	    "EMAIL" IS NOT NULL	
HR	EMP_HIRE_DATE_NN	EMPLOYEES	C	HIRE_DATE	"HIRE_DATE" IS NOT NULL	
HR	EMP_JOB_NN	        EMPLOYEES	C	JOB_ID	    "JOB_ID" IS NOT NULL	
HR	EMP_SALARY_MIN	    EMPLOYEES	C	SALARY	    salary > 0	
HR	EMP_EMAIL_UK	    EMPLOYEES	U	EMAIL		
HR	EMP_EMP_ID_PK	    EMPLOYEES	P	EMPLOYEE_ID		
HR	EMP_DEPT_FK	        EMPLOYEES	R	DEPARTMENT_ID		                NO ACTION
HR	EMP_JOB_FK	        EMPLOYEES	R	JOB_ID		                        NO ACTION
HR	EMP_MANAGER_FK	    EMPLOYEES	R	MANAGER_ID		                    NO ACTION
*/

-- EMPLOYEES01 테이블 생성
CREATE TABLE EMPLOYEES01
( EMPLOYEE_ID     NUMBER(6)    
, FIRST_NAME      VARCHAR2(20) 
, LAST_NAME       VARCHAR2(25) CONSTRAINT EMP01_LAST_NAME_NN NOT NULL
, EMAIL           VARCHAR2(25) CONSTRAINT EMP01_EMAIL_NN NOT NULL
, PHONE_NUMBER    VARCHAR2(20) 
, HIRE_DATE       DATE         CONSTRAINT EMP01_HIRE_DATE_NN NOT NULL
, JOB_ID          VARCHAR2(10) CONSTRAINT EMP01_JOB_NN NOT NULL
, SALARY          NUMBER(8,2)  
, COMMISSION_PCT  NUMBER(2,2)  
, MANAGER_ID      NUMBER(6)    
, DEPARTMENT_ID   NUMBER(4)
, CONSTRAINT EMP01_SALARY_MIN CHECK (SALARY > 0)
, CONSTRAINT EMP01_EMAIL_UK UNIQUE(EMAIL)
, CONSTRAINT EMP01_EMP_ID_PK PRIMARY KEY(EMPLOYEE_ID)
, CONSTRAINT EMP01_DEPT_FK FOREIGN KEY(DEPARTMENT_ID)
             REFERENCES DEPARTMENTS01(DEPARTMENT_ID)
, CONSTRAINT EMP01_JOB_FK FOREIGN KEY(JOB_ID)
             REFERENCES JOBS01(JOB_ID)
, CONSTRAINT EMP01_MANAGER_FK FOREIGN KEY(MANAGER_ID)
             REFERENCES EMPLOYEES01(EMPLOYEE_ID)
);
--==>> 오류 발생.... 해결....해야 함...ㅠㅠ → 참조 키 FK 는 다른 테이블의 UK 혹은 PK 만 참조 가능..!  
--     EMP_MANAGER_FK01 → 자기자신 EMPLOYEES01 의 PK 인 EMPLOYEE_ID 를 참조하는 FK ...!!
--     즉, REFERENCES DEPARTMENTS01(MANAGER_ID) → REFERENCES EMPLOYEES01(EMPLOYEE_ID) 

--==>> 오류 해결 후 : Table EMPLOYEES01이(가) 생성되었습니다.

SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEES';
/*
HR	EMP_MANAGER_FK	R	EMPLOYEES		HR	EMP_EMP_ID_PK	NO ACTION	ENABLED	NOT DEFERRABLE	IMMEDIATE	VALIDATED	USER NAME			14/05/29				
*/


-- 생성후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='EMPLOYEES01';
/*
HR	EMP01_LAST_NAME_NN	EMPLOYEES01	C	LAST_NAME	"LAST_NAME" IS NOT NULL	
HR	EMP01_EMAIL_NN	    EMPLOYEES01	C	EMAIL	    "EMAIL" IS NOT NULL	
HR	EMP01_HIRE_DATE_NN	EMPLOYEES01	C	HIRE_DATE	"HIRE_DATE" IS NOT NULL	
HR	EMP01_JOB_NN	    EMPLOYEES01	C	JOB_ID	    "JOB_ID" IS NOT NULL	
HR	EMP01_SALARY_MIN	EMPLOYEES01	C	SALARY	    SALARY > 0	
HR	EMP01_EMP_ID_PK	    EMPLOYEES01	P	EMPLOYEE_ID		
HR	EMP01_EMAIL_UK	    EMPLOYEES01	U	EMAIL		
HR	EMP01_DEPT_FK	    EMPLOYEES01	R	DEPARTMENT_ID		                    NO ACTION
HR	EMP01_JOB_FK	    EMPLOYEES01	R	JOB_ID		                            NO ACTION
HR	EMP01_MANAGER_FK	EMPLOYEES01	R	MANAGER_ID		                        NO ACTION
*/


------------------------------------------------------------------------

-- 기존 JOB_HISTORY 테이블 구조 확인
DESC JOB_HISTORY;
/*
이름            널?       유형           
------------- -------- ------------ 
EMPLOYEE_ID   NOT NULL NUMBER(6)    
START_DATE    NOT NULL DATE         
END_DATE      NOT NULL DATE         
JOB_ID        NOT NULL VARCHAR2(10) 
DEPARTMENT_ID          NUMBER(4)    
*/

-- 기존 JOB_HISTORY 테이블 제약조건 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='JOB_HISTORY';
/*
HR	JHIST_EMPLOYEE_NN	    JOB_HISTORY	C	EMPLOYEE_ID	"EMPLOYEE_ID" IS NOT NULL	
HR	JHIST_START_DATE_NN	    JOB_HISTORY	C	START_DATE	"START_DATE" IS NOT NULL	
HR	JHIST_END_DATE_NN	    JOB_HISTORY	C	END_DATE	"END_DATE" IS NOT NULL	
HR	JHIST_JOB_NN	        JOB_HISTORY	C	JOB_ID	    "JOB_ID" IS NOT NULL	
HR	JHIST_DATE_INTERVAL	    JOB_HISTORY	C	START_DATE	end_date > start_date	
HR	JHIST_DATE_INTERVAL	    JOB_HISTORY	C	END_DATE	end_date > start_date	
HR	JHIST_EMP_ID_ST_DATE_PK	JOB_HISTORY	P	EMPLOYEE_ID		
HR	JHIST_EMP_ID_ST_DATE_PK	JOB_HISTORY	P	START_DATE		
HR	JHIST_JOB_FK	        JOB_HISTORY	R	JOB_ID		                        NO ACTION
HR	JHIST_EMP_FK	        JOB_HISTORY	R	EMPLOYEE_ID		                    NO ACTION
HR	JHIST_DEPT_FK	        JOB_HISTORY	R	DEPARTMENT_ID		                NO ACTION
*/

-- JOB_HISTORY01 테이블 생성
CREATE TABLE JOB_HISTORY01
( EMPLOYEE_ID         NUMBER(6)    CONSTRAINT JHIST01_EMPLOYEE_NN NOT NULL
, START_DATE          DATE         CONSTRAINT JHIST01_START_DATE_NN NOT NULL
, END_DATE            DATE         CONSTRAINT JHIST01_END_DATE_NN NOT NULL
, JOB_ID              VARCHAR2(10) CONSTRAINT JHIST01_JOB_NN NOT NULL
, DEPARTMENT_ID       NUMBER(4)
, CONSTRAINT JHIST01_EMP_ID_ST_DATE_PK PRIMARY KEY(EMPLOYEE_ID, START_DATE)
, CONSTRAINT JHIST01_DATE_INTERVAL CHECK(end_date > start_date)
, CONSTRAINT JHIST01_JOB_FK FOREIGN KEY(JOB_ID)
             REFERENCES JOBS01(JOB_ID)
, CONSTRAINT JHIST01_EMP_FK FOREIGN KEY(EMPLOYEE_ID)
             REFERENCES EMPLOYEES01(EMPLOYEE_ID)
, CONSTRAINT JHIST01_DEPT_FK FOREIGN KEY(DEPARTMENT_ID)
             REFERENCES DEPARTMENTS01(DEPARTMENT_ID)
);
--> PK : EMPLOYEE_ID, START_DATE
--> FK : JOBS, EMPLOYEES, DEPARTMENTS
--==>> Table JOB_HISTORY01이(가) 생성되었습니다.


SELECT *
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'JOB_HISTORY';


-- 생성후 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='JOB_HISTORY01';
/*
HR	JHIST01_EMPLOYEE_NN	        JOB_HISTORY01	C	EMPLOYEE_ID	"EMPLOYEE_ID" IS NOT NULL	
HR	JHIST01_START_DATE_NN	    JOB_HISTORY01	C	START_DATE	"START_DATE" IS NOT NULL	
HR	JHIST01_END_DATE_NN	        JOB_HISTORY01	C	END_DATE	"END_DATE" IS NOT NULL	
HR	JHIST01_JOB_NN	            JOB_HISTORY01	C	JOB_ID	    "JOB_ID" IS NOT NULL	
HR	JHIST01_DATE_INTERVAL	    JOB_HISTORY01	C	START_DATE	end_date > start_date	
HR	JHIST01_DATE_INTERVAL	    JOB_HISTORY01	C	END_DATE	end_date > start_date	
HR	JHIST01_EMP_ID_ST_DATE_PK	JOB_HISTORY01	P	EMPLOYEE_ID		
HR	JHIST01_EMP_ID_ST_DATE_PK	JOB_HISTORY01	P	START_DATE		
HR	JHIST01_JOB_FK	            JOB_HISTORY01	R	JOB_ID		                            NO ACTION
HR	JHIST01_EMP_FK	            JOB_HISTORY01	R	EMPLOYEE_ID		                        NO ACTION
HR	JHIST01_DEPT_FK	            JOB_HISTORY01	R	DEPARTMENT_ID		                    NO ACTION
*/



=================================================
-- 커멘트 입력
=================================================

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='REGIONS';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='REGIONS';

--> 커멘트 정보 없음.


------------------------------------------------------------------------

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='COUNTRIES';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='COUNTRIES';


-- 테이블 레벨 커멘트 입력
COMMENT ON TABLE COUNTRIES01 IS 'country table. Contains 25 rows. References with locations table.';
--==>> Comment이(가) 생성되었습니다.

-- 컬럼 레벨 커멘트 입력 
COMMENT ON COLUMN COUNTRIES01.COUNTRY_ID IS 'Primary key of countries table.';
COMMENT ON COLUMN COUNTRIES01.COUNTRY_NAME IS 'Country name';
COMMENT ON COLUMN COUNTRIES01.REGION_ID IS 'Region ID for the country. Foreign key to region_id column in the departments table.';
--==>> Comment이(가) 생성되었습니다. * 3


-- 커멘트 추가 후 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='COUNTRIES01';

-- 커멘트 추가 후 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='COUNTRIES01';


------------------------------------------------------------------------

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='LOCATIONS';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='LOCATIONS';


-- 테이블 레벨 커멘트 입력
COMMENT ON TABLE LOCATIONS01 IS 'Locations table that contains specific address of a specific office,
warehouse, and/or production site of a company. Does not store addresses /
locations of customers. Contains 23 rows; references with the
departments and countries tables. ';
--==>> Comment이(가) 생성되었습니다.

-- 컬럼 레벨 커멘트 입력 
COMMENT ON COLUMN LOCATIONS01.LOCATION_ID IS 'Primary key of locations table';
COMMENT ON COLUMN LOCATIONS01.STREET_ADDRESS IS 'Street address of an office, warehouse, or production site of a company. Contains building number and street name';
COMMENT ON COLUMN LOCATIONS01.POSTAL_CODE IS 'Postal code of the location of an office, warehouse, or production site of a company. ';
COMMENT ON COLUMN LOCATIONS01.CITY IS 'A not null column that shows city where an office, warehouse, or production site of a company is located. ';
COMMENT ON COLUMN LOCATIONS01.STATE_PROVINCE IS 'State or Province where an office, warehouse, or production site of a company is located.';
COMMENT ON COLUMN LOCATIONS01.COUNTRY_ID IS 'Country where an office, warehouse, or production site of a company is located. Foreign key to country_id column of the countries table.';
--==>> Comment이(가) 생성되었습니다. * 6


-- 커멘트 추가 후 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='LOCATIONS01';

-- 커멘트 추가 후 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='LOCATIONS01';


------------------------------------------------------------------------

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='JOBS';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='JOBS';


-- 테이블 레벨 커멘트 입력
COMMENT ON TABLE JOBS01 IS 'jobs table with job titles and salary ranges. Contains 19 rows.
References with employees and job_history table.';
--==>> Comment이(가) 생성되었습니다.

-- 컬럼 레벨 커멘트 입력 
COMMENT ON COLUMN JOBS01.JOB_ID IS 'Primary key of jobs table.';
COMMENT ON COLUMN JOBS01.JOB_TITLE IS 'A not null column that shows job title, e.g. AD_VP, FI_ACCOUNTANT';
COMMENT ON COLUMN JOBS01.MIN_SALARY IS 'Minimum salary for a job title.';
COMMENT ON COLUMN JOBS01.MAX_SALARY IS 'Maximum salary for a job title';
--==>> Comment이(가) 생성되었습니다. * 4


-- 커멘트 추가 후 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='JOBS01';

-- 커멘트 추가 후 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='JOBS01';

------------------------------------------------------------------------

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='DEPARTMENTS';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='DEPARTMENTS';


-- 테이블 레벨 커멘트 입력
COMMENT ON TABLE DEPARTMENTS01 IS 'Departments table that shows details of departments where employees work. Contains 27 rows; references with locations, employees, and job_history tables.';
--==>> Comment이(가) 생성되었습니다.

-- 컬럼 레벨 커멘트 입력 
COMMENT ON COLUMN DEPARTMENTS01.DEPARTMENT_ID IS 'Primary key column of departments table.';
COMMENT ON COLUMN DEPARTMENTS01.DEPARTMENT_NAME IS 'A not null column that shows name of a department. Administration, Marketing, Purchasing, Human Resources, Shipping, IT, Executive, PublicRelations, Sales, Finance, and Accounting. ';
COMMENT ON COLUMN DEPARTMENTS01.MANAGER_ID IS 'Manager_id of a department. Foreign key to employee_id column of employees table. The manager_id column of the employee table references this column.';
COMMENT ON COLUMN DEPARTMENTS01.LOCATION_ID IS 'Location id where a department is located. Foreign key to location_id column of locations table.';
--==>> Comment이(가) 생성되었습니다. * 4

-- 커멘트 추가 후 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='DEPARTMENTS01';

-- 커멘트 추가 후 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='DEPARTMENTS01';


------------------------------------------------------------------------

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='EMPLOYEES';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='EMPLOYEES';


-- 테이블 레벨 커멘트 입력
COMMENT ON TABLE EMPLOYEES01 IS 'employees table. Contains 107 rows. References with departments, jobs, job_history tables. Contains a self reference.';
--==>> Comment이(가) 생성되었습니다.

-- 컬럼 레벨 커멘트 입력 
COMMENT ON COLUMN EMPLOYEES01.EMPLOYEE_ID IS 'Primary key of employees table.';
COMMENT ON COLUMN EMPLOYEES01.FIRST_NAME IS 'First name of the employee. A not null column.';
COMMENT ON COLUMN EMPLOYEES01.LAST_NAME IS 'Last name of the employee. A not null column.';
COMMENT ON COLUMN EMPLOYEES01.EMAIL IS 'Email id of the employee';
COMMENT ON COLUMN EMPLOYEES01.PHONE_NUMBER IS 'Phone number of the employee; includes country code and area code';
COMMENT ON COLUMN EMPLOYEES01.HIRE_DATE IS 'Date when the employee started on this job. A not null column.';
COMMENT ON COLUMN EMPLOYEES01.JOB_ID IS 'Current job of the employee; foreign key to job_id column of the jobs table. A not null column.';
COMMENT ON COLUMN EMPLOYEES01.SALARY IS 'Monthly salary of the employee. Must be greater than zero (enforced by constraint emp_salary_min)';
COMMENT ON COLUMN EMPLOYEES01.COMMISSION_PCT IS 'Commission percentage of the employee; Only employees in sales department elgible for commission percentage';
COMMENT ON COLUMN EMPLOYEES01.MANAGER_ID IS 'Manager id of the employee; has same domain as manager_id in departments table. Foreign key to employee_id column of employees table.(useful for reflexive joins and CONNECT BY query)';
COMMENT ON COLUMN EMPLOYEES01.DEPARTMENT_ID IS 'Department id where employee works; foreign key to department_id column of the departments table';
--==>> Comment이(가) 생성되었습니다. * 11


-- 커멘트 추가 후 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='EMPLOYEES01';

-- 커멘트 추가 후 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='EMPLOYEES01';



------------------------------------------------------------------------

-- 커멘트 정보 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='JOB_HISTORY';

-- 커멘트 정보 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='JOB_HISTORY';


-- 테이블 레벨 커멘트 입력
COMMENT ON TABLE JOB_HISTORY01 IS 'Table that stores job history of the employees. If an employee
changes departments within the job or changes jobs within the department,
new rows get inserted into this table with old job information of the
employee. Contains a complex primary key: employee_id+start_date.
Contains 25 rows. References with jobs, employees, and departments tables.';
--==>> Comment이(가) 생성되었습니다.

-- 컬럼 레벨 커멘트 입력 
COMMENT ON COLUMN JOB_HISTORY01.EMPLOYEE_ID IS 'A not null column in the complex primary key employee_id+start_date.
Foreign key to employee_id column of the employee table';
COMMENT ON COLUMN JOB_HISTORY01.START_DATE IS 'A not null column in the complex primary key employee_id+start_date.
Must be less than the end_date of the job_history table. (enforced by
constraint jhist_date_interval)';
COMMENT ON COLUMN JOB_HISTORY01.END_DATE IS 'Last day of the employee in this job role. A not null column. Must be
greater than the start_date of the job_history table.
(enforced by constraint jhist_date_interval)';
COMMENT ON COLUMN JOB_HISTORY01.JOB_ID IS 'Job role in which the employee worked in the past; foreign key to
job_id column in the jobs table. A not null column.';
COMMENT ON COLUMN JOB_HISTORY01.DEPARTMENT_ID IS 'Department id in which the employee worked in the past; foreign key to deparment_id column in the departments table';
--==>> Comment이(가) 생성되었습니다. * 5


-- 커멘트 추가 후 확인(테이블)
SELECT *
FROM USER_TAB_COMMENTS
WHERE TABLE_NAME='JOB_HISTORY01';

-- 커멘트 추가 후 확인(컬럼)
SELECT *
FROM USER_COL_COMMENTS
WHERE TABLE_NAME='JOB_HISTORY01';




=================================================
-- FOREIGN KEY 제거
=================================================
-- COUNTRIES01 테이블 FK 제약조건 제거
ALTER TABLE COUNTRIES01
DROP CONSTRAINT COUNTR01_REG_FK;

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='COUNTRIES01';


-- LOCATIONS01 테이블 FK 제약조건 제거
ALTER TABLE LOCATIONS01 
DROP CONSTRAINT LOC01_C_ID_FK;

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='LOCATIONS01';


-- DEPARTMENTS01  테이블 FK 제약조건 제거
ALTER TABLE DEPARTMENTS01  
DROP CONSTRAINT DEPT01_LOC_FK;

ALTER TABLE DEPARTMENTS01  
DROP CONSTRAINT DEPT01_MGR_FK;

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='DEPARTMENTS01';


-- EMPLOYEES01 테이블 FK 제약조건 제거
ALTER TABLE EMPLOYEES01   
DROP CONSTRAINT EMP01_DEPT_FK;

ALTER TABLE EMPLOYEES01   
DROP CONSTRAINT EMP01_JOB_FK;

ALTER TABLE EMPLOYEES01   
DROP CONSTRAINT EMP01_MANAGER_FK;

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='EMPLOYEES01';


-- JOB_HISTORY01 테이블 FK 제약조건 제거
ALTER TABLE JOB_HISTORY01   
DROP CONSTRAINT JHIST01_JOB_FK;

ALTER TABLE JOB_HISTORY01   
DROP CONSTRAINT JHIST01_EMP_FK;

ALTER TABLE JOB_HISTORY01   
DROP CONSTRAINT JHIST01_DEPT_FK;

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='JOB_HISTORY01';




===============================================
-- 데이터 입력
===============================================
-- REGIONS01 / COUNTRIES01 / LOCATIONS01 / JOBS01 / DEPARTMENTS01 /  EMPLOYEES01  / JOB_HISTORY01  

--REGIONS01 데이터
--INSERT INTO REGIONS01(REGION_ID, REGION_NAME) VALUES(); 

INSERT INTO REGIONS01(REGION_ID, REGION_NAME) VALUES(1, 'Europe');
INSERT INTO REGIONS01(REGION_ID, REGION_NAME) VALUES(2, 'Americas');
INSERT INTO REGIONS01(REGION_ID, REGION_NAME) VALUES(3, 'Asia');
INSERT INTO REGIONS01(REGION_ID, REGION_NAME) VALUES(4, 'Middle East and Africa');
--==>> 1 행 이(가) 삽입되었습니다. * 4

--확인
SELECT *
FROM REGIONS01;


--COUNTRIES01 데이터
--INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES();

INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('AR','Argentina',2); --1
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('AU','Australia',3); --2
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('BE','Belgium',1); --3
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('BR','Brazil',2); --4
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('CA','Canada',2); --5
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('CH','Switzerland',1); --6
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('CN','China',3); --7
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('DE','Germany',1); --8
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('DK','Denmark',1); --9
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('EG','Egypt',4); --10
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('FR','France',1); --11
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('IL','Israel',4); --12
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('IN','India',3); --13
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('IT','Italy',1); --14
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('JP','Japan',3); --15
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('KW','Kuwait',4); --16
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('ML','Malaysia',3); --17
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('MX','Mexico',2); --18
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('NG','Nigeria',4); --19
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('NL','Netherlands',1); --20
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('SG','Singapore',3); --21
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('UK','United Kingdom',1); --22
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('US','United States of America',2); --23
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('ZM','Zambia',4); --24
INSERT INTO COUNTRIES01(COUNTRY_ID, COUNTRY_NAME, REGION_ID) VALUES('ZW','Zimbabwe',4); --25
--==>> 1 행 이(가) 삽입되었습니다. * 25

--확인
SELECT *
FROM COUNTRIES01;


--LOCATIONS01 데이터
--INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) VALUES();

INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1000, '1297 Via Cola di Rie', '00989', 'Roma', NULL, 'IT');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1100, '93091 Calle della Testa', '10934', 'Venice', NULL, 'IT');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1200, '2017 Shinjuku-ku', '1689', 'Tokyo', 'Tokyo Prefecture', 'JP');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1300, '9450 Kamiya-cho', '6823', 'Hiroshima', NULL, 'JP');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1400, '2014 Jabberwocky Rd', '26192', 'Southlake', 'Texas', 'US');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1500, '2011 Interiors Blvd', '99236', 'South San Francisco', 'California', 'US');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1600, '2007 Zagora St', '50090', 'South Brunswick', 'New Jersey', 'US');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1700, '2004 Charade Rd', '98199', 'Seattle', 'Washington', 'US');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1800, '147 Spadina Ave', 'M5V 2L7', 'Toronto', 'Ontario', 'CA');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(1900, '6092 Boxwood St', 'YSW 9T2', 'Whitehorse', 'Yukon', 'CA');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2000, '40-5-12 Laogianggen', '190518', 'Beijing', NULL, 'CN');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2100, '1298 Vileparle (E)', '490231', 'Bombay', 'Maharashtra', 'IN');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2200, '12-98 Victoria Street', '2901', 'Sydney', 'New South Wales', 'AU');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2300, '198 Clementi North', '540198', 'Singapore', NULL, 'SG');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2400, '8204 Arthur St', NULL, 'London', NULL, 'UK');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2500, 'Magdalen Centre, The Oxford Science Park', 'OX9 9ZB', 'Oxford', 'Oxford', 'UK');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2600, '9702 Chester Road', '09629850293', 'Stretford', 'Manchester', 'UK');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2700, 'Schwanthalerstr. 7031', '80925', 'Munich', 'Bavaria', 'DE');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2800, 'Rua Frei Caneca 1360 ', '01307-002', 'Sao Paulo', 'Sao Paulo', 'BR');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(2900, '20 Rue des Corps-Saints', '1730', 'Geneva', 'Geneve', 'CH');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(3000, 'Murtenstrasse 921', '3095', 'Bern', 'BE', 'CH');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(3100, 'Pieter Breughelstraat 837', '3029SK', 'Utrecht', 'Utrecht', 'NL');
INSERT INTO LOCATIONS01(LOCATION_ID, STREET_ADDRESS, POSTAL_CODE, CITY, STATE_PROVINCE, COUNTRY_ID) 
VALUES(3200, 'Mariano Escobedo 9991', '11932', 'Mexico City', 'Distrito Federal,', 'MX');
--==>> 1 행 이(가) 삽입되었습니다. * 23

--확인
SELECT *
FROM LOCATIONS01;


--JOBS01 데이터
--INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES();

INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('AD_PRES', 'President', 20080, 40000);                   
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('AD_VP', 'Administration_Vice_President', 15000, 30000); 
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('AD_ASST', 'Administration_Assistant', 3000, 6000);      
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('FI_MGR', 'Finance_Manager', 8200, 16000);                
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('FI_ACCOUNT', 'Accountant', 4200, 9000);                 
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('AC_MGR', 'Accounting_Manager', 8200, 16000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('AC_ACCOUNT', 'Public_Accountant', 4200, 9000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('SA_MAN', 'Sales_Manager', 10000, 20080);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('SA_REP', 'Sales_Representative', 6000, 12008);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('PU_MAN', 'Purchasing_Manager', 8000, 15000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('PU_CLERK', 'Purchasing_Clerk', 2500, 5500);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('ST_MAN', 'Stock_Manager', 5500, 8500);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('ST_CLERK', 'Stock_Clerk', 2008, 5000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('SH_CLERK', 'Shipping_Clerk', 2500, 5500);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('IT_PROG', 'Programmer', 4000, 10000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('MK_MAN', 'Marketing_Manager', 9000, 15000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('MK_REP', 'Marketing_Repersentative', 4000, 9000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('HR_REP', 'Human_Resources_Representative', 4000, 9000);
INSERT INTO JOBS01(JOB_ID, JOB_TITLE, MIN_SALARY, MAX_SALARY) VALUES('PR_REP', 'Public_Relations_Representative', 4500, 10500);
--==>> 1 행 이(가) 삽입되었습니다. * 19

--확인
SELECT *
FROM JOBS01;



--DEPARTMENTS01 데이터
--INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES();

INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(10, 'Administration', 200, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(20, 'Marketing', 201, 1800);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(30, 'Purchasing', 114, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(40, 'Human Resources', 203, 2400);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(50, 'Shipping', 121, 1500);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(60, 'IT', 103, 1400);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(70, 'Public Relations', 204, 2700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(80, 'Sales', 145, 2500);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(90, 'Executive', 100, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(100, 'Finance', 108, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(110, 'Accounting', 205, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(120, 'Treasury', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(130, 'Corporate Tax', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(140, 'Control And Credit', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(150, 'Shareholder Services', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(160, 'Benefits', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(170, 'Manufacturing', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(180, 'Construction', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(190, 'Contracting', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(200, 'Operations', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(210, 'IT Support', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(220, 'NOC', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(230, 'IT Helpdesk', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(240, 'Government Sales', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(250, 'Retail Sales', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(260, 'Recruiting', NULL, 1700);
INSERT INTO DEPARTMENTS01(DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID) VALUES(270, 'Payroll', NULL, 1700);
--==>> 1 행 이(가) 삽입되었습니다. * 19

--확인
SELECT *
FROM DEPARTMENTS01;


--EMPLOYEES01 데이터
--INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES();

INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(100, 'Steven',       'King',       'SKING',         '515.123.4567',   TO_DATE('2003/06/17', 'YY/MM/DD'),   'AD_PRES',       24000,   NULL,   NULL, 90);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(101, 'Neena',       'Kochhar',  'NKOCHHAR',       '515.123.4568',   TO_DATE('2005/09/21', 'YY/MM/DD'),   'AD_VP',           17000,   NULL,   100,  90);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(102, 'Lex',        'De Haan',   'LDEHAAN',          '515.123.4569',   TO_DATE('2001/01/13', 'YY/MM/DD'),   'AD_VP',           17000,   NULL,   100,  90);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(103, 'Alexander',   'Hunold',   'AHUNOLD',        '590.423.4567',   TO_DATE('2006/01/03', 'YY/MM/DD'),   'IT_PROG',       9000,   NULL,   102,  60);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(104, 'Bruce',       'Ernst',       'BERNST',         '590.423.4568',   TO_DATE('2007/05/21', 'YY/MM/DD'),   'IT_PROG',       6000,   NULL,   103,  60);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(105, 'David',       'Austin',   'DAUSTIN',       '590.423.4569',   TO_DATE('2005/06/25', 'YY/MM/DD'),   'IT_PROG',       4800,   NULL,   103,  60); --확인바람
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(106, 'Valli',       'Pataballa',   'VPATABAL',      '590.423.4560',   TO_DATE('2006/02/05', 'YY/MM/DD'),   'IT_PROG',       4800,   NULL,   103,  60);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(107, 'Diana',       'Lorentz',   'DLORENTZ',      '590.423.5567',   TO_DATE('2007/02/07', 'YY/MM/DD'),   'IT_PROG',       4200,   NULL,   103,  60);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(108, 'Nancy',       'Greenberg',   'NGREENBE',      '515.124.4569',   TO_DATE('2002/08/17', 'YY/MM/DD'),   'FI_MGR',       12008,   NULL,   101,  100);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(109, 'Daniel',       'Faviet',   'DFAVIET',       '515.124.4169',   TO_DATE('2002/08/16', 'YY/MM/DD'),   'FI_ACCOUNT',   9000,   NULL,   108,  100);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(110, 'John',       'Chen',       'JCHEN',            '515.124.4269',   TO_DATE('2005/09/28', 'YY/MM/DD'),   'FI_ACCOUNT',   8200,   NULL,   108,  100);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(111, 'Ismael',       'Sciarra',   'ISCIARRA',      '515.124.4369',   TO_DATE('2005/09/30', 'YY/MM/DD'),   'FI_ACCOUNT',   7700,   NULL,   108,  100);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(112, 'Jose Manuel',   'Urman',       'JMURMAN',      '515.124.4469',   TO_DATE('2006/03/07', 'YY/MM/DD'),   'FI_ACCOUNT',   7800,   NULL,   108,  100);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(113, 'Luis',       'Popp',       'LPOPP',            '515.124.4567',   TO_DATE('2007/12/07', 'YY/MM/DD'),   'FI_ACCOUNT',   6900,   NULL,   108,  100);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(114, 'Den',       'Raphaely',   'DRAPHEAL',         '515.127.4561',   TO_DATE('2002/12/07', 'YY/MM/DD'),   'PU_MAN',       11000,   NULL,   100,  30);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(115, 'Alexander',   'Khoo',       'AKHOO',        '515.127.4562',   TO_DATE('2003/05/18', 'YY/MM/DD'),   'PU_CLERK',       3100,   NULL,   114,  30);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(116, 'Shelli',   'Baida',       'SBAIDA',            '515.127.4563',   TO_DATE('2005/12/24', 'YY/MM/DD'),   'PU_CLERK',       2900,   NULL,   114,  30);--
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(117, 'Sigal',   'Tobias',       'STOBIAS',        '515.127.4564',   TO_DATE('2005/07/24', 'YY/MM/DD'),   'PU_CLERK',       2800,   NULL,   114,  30);--
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(118, 'Guy',   'Himuro',       'GHIMURO',            '515.127.4565',   TO_DATE('2006/11/15', 'YY/MM/DD'),   'PU_CLERK',       2600,   NULL,   114,  30);--
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(119, 'Karen',   'Colmenares',       'KCOLMENA',  '515.127.4566',   TO_DATE('2007/08/10', 'YY/MM/DD'),   'PU_CLERK',       2500,   NULL,   114,  30);--
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(120, 'Matthew',   'Weiss',       'MWEISS',            '650.123.1234',   TO_DATE('2004/07/18', 'YY/MM/DD'),   'ST_MAN',       8000,   NULL,   100,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(121, 'Adam',   'Fripp',       'AFRIPP',            '650.123.2234',   TO_DATE('2005/04/10', 'YY/MM/DD'),   'ST_MAN',       8200,   NULL,   100,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(122, 'Payam',   'Kaufling',       'PKAUFLIN',  '650.123.3234',   TO_DATE('2003/05/01', 'YY/MM/DD'),   'ST_MAN',       7900,   NULL,   100,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(123, 'Shanta',   'Vollman',       'SVOLLMAN',  '650.123.4234',   TO_DATE('2005/10/10', 'YY/MM/DD'),   'ST_MAN',       6500,   NULL,   100,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(124, 'Kevin',   'Mourgos',       'KMOURGOS',  '650.123.5234',   TO_DATE('2007/11/16', 'YY/MM/DD'),   'ST_MAN',       5800,   NULL,   100,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(125, 'Julia',   'Nayer',       'JNAYER',  '650.124.1214',   TO_DATE('2005/07/16', 'YY/MM/DD'),   'ST_CLERK',       3200,   NULL,   120,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(126, 'Irene',   'Mikkilineni',       'IMIKKILI',  '650.124.1224',   TO_DATE('2006/09/28', 'YY/MM/DD'),   'ST_CLERK',       2700,   NULL,   120,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(127, 'James',   'Landry',       'JLANDRY',  '650.124.1334',   TO_DATE('2007/01/14', 'YY/MM/DD'),   'ST_CLERK',       2400,   NULL,   120,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(128, 'Steven',   'Markle',       'SMARKLE',  '650.124.1434',   TO_DATE('2008/03/08', 'YY/MM/DD'),   'ST_CLERK',       2200,   NULL,   120,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(129, 'Laura',   'Bissot',       'LBISSOT',  '650.124.5234',   TO_DATE('2005/08/20', 'YY/MM/DD'),   'ST_CLERK',       3300,   NULL,   121,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(130, 'Mozhe',   'Atkinson',       'MATKINSO',  '650.124.6234',   TO_DATE('2005/10/30', 'YY/MM/DD'),   'ST_CLERK',       2800,   NULL,   121,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(131, 'James',   'Marlow',       'JAMRLOW',  '650.124.7234',   TO_DATE('2005/02/16', 'YY/MM/DD'),   'ST_CLERK',       2500,   NULL,   121,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(132, 'TJ',   'Olson',       'TJOLSON',  '650.124.8234',   TO_DATE('2007/04/10', 'YY/MM/DD'),   'ST_CLERK',       2100,   NULL,   121,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(133, 'Jason',   'Mallin',       'JMALLIN',  '650.127.1934',   TO_DATE('2004/06/14', 'YY/MM/DD'),   'ST_CLERK',       3300,   NULL,   122,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(134, 'Michael',   'Rogers',       'MROGERS',  '650.127.1834',   TO_DATE('2006/08/26', 'YY/MM/DD'),   'ST_CLERK',       2900,   NULL,   122,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(135, 'Ki',   'Gee',       'KGEE',  '650.127.1734',   TO_DATE('2007/12/12', 'YY/MM/DD'),   'ST_CLERK',       2400,   NULL,   122,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(136, 'Hazel',   'Philtanker',       'HPHILTAN',  '650.127.1634',   TO_DATE('2008/02/06', 'YY/MM/DD'),   'ST_CLERK',       2200,   NULL,   122,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(137, 'Renske',   'Ladwig',       'RLADWIG',  '650.121.1234',   TO_DATE('2003/07/14', 'YY/MM/DD'),   'ST_CLERK',       3600,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(138, 'Stephen',   'Stiles',       'SSTILES',  '650.121.2034',   TO_DATE('2005/10/26', 'YY/MM/DD'),   'ST_CLERK',       3200,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(139, 'John',   'Seo',       'JSEO',  '650.121.2019',   TO_DATE('2006/02/12', 'YY/MM/DD'),   'ST_CLERK',       2700,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(140, 'Joshua',   'Patel',       'JPATEL',  '650.121.1834',   TO_DATE('2006/04/06', 'YY/MM/DD'),   'ST_CLERK',       2500,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(141, 'Trenna',   'Rajs',       'TRAJS',  '650.121.8009',   TO_DATE('2003/10/17', 'YY/MM/DD'),   'ST_CLERK',       3500,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(142, 'Curtis',   'Davies',       'CDAVIES',  '650.121.2994',   TO_DATE('2005/01/29', 'YY/MM/DD'),   'ST_CLERK',       3100,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(143, 'Randall',   'Matos',       'RMATOS',  '650.121.2874',   TO_DATE('2006/03/15', 'YY/MM/DD'),   'ST_CLERK',       2600,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(144, 'Peter',   'Vargas',       'PVARGAS',  '650.121.2004',   TO_DATE('2006/07/09', 'YY/MM/DD'),   'ST_CLERK',       2500,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(145,   'John',   'Russell',   'JRUSSEL',   '011.44.1344.429268',   TO_DATE('2004/10/01','YY/MM/DD'),   'SA_MAN',   14000,  0.4,   100,   80); --46
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(146,   'Karen',   'Partners',   'KPARTNER',   '011.44.1344.467268',   TO_DATE('2005/01/05','YY/MM/DD'),   'SA_MAN',   13500,   0.3,   100,   80); --47
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(147,   'Alberto',   'Errazuriz',   'AERRAZUR',   '011.44.1344.429278',   TO_DATE('2005/03/10','YY/MM/DD'),   'SA_MAN',   12000,   0.3,   100,   80); --48
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(148,   'Gerald',   'Cambrault',   'GCAMBRAU',   '011.44.1344.619268',   TO_DATE('2007/10/15','YY/MM/DD'),   'SA_MAN',   11000,   0.3,   100,   80); --49
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(149,   'Eleni',   'Zlotkey',   'EZLOTKEY',   '011.44.1344.429018',   TO_DATE('2008/01/29','YY/MM/DD'),   'SA_MAN',   10500,   0.2,   100,   80); --50
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(150,   'Peter',   'Tucker',   'PTUCKER',   '011.44.1344.129268',   TO_DATE('2005/01/30','YY/MM/DD'),   'SA_REP',   10000,   0.3,   145,   80); --51
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(151,   'David',   'Bernstein',   'DBERNSTE',   '011.44.1344.345268',   TO_DATE('2005/03/24','YY/MM/DD'),   'SA_REP',   9500,   0.25,   145,   80); --52
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(152,   'Peter',   'Hall',   'PHALL',   '011.44.1344.478968',   TO_DATE('2005/08/20','YY/MM/DD'),   'SA_REP',   9000,   0.25,   145,   80); --53
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(153,   'Christopher',   'Olsen',   'COLSEN',   '011.44.1344.498718',   TO_DATE('2006/03/30','YY/MM/DD'),   'SA_REP',   8000,   0.2,   145,   80); --54
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(154,   'Nanette',   'Cambrault',   'NCAMBRAU',   '011.44.1344.987668',   TO_DATE('2006/12/09','YY/MM/DD'),   'SA_REP',   7500,   0.2,   145,   80); --55
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(155,   'Oliver',   'Tuvault',   'OTUVAULT',   '011.44.1344.486508',   TO_DATE('2007/11/23','YY/MM/DD'),   'SA_REP',   7000,   0.15,   145,   80); --56
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(156,   'Janette',   'King',   'JKING',   '011.44.1345.429268',   TO_DATE('2004/01/30','YY/MM/DD'),   'SA_REP',   10000,   0.35,   146,   80); --57
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(157,   'Patrick',   'Sully',   'PSULLY',   '011.44.1345.929268',   TO_DATE('2004/03/04','YY/MM/DD'),   'SA_REP',   9500,   0.35,   146,   80); --58
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(158,   'Allan',   'McEwen',   'AMCEWEN',   '011.44.1345.829268',   TO_DATE('2004/08/01','YY/MM/DD'),   'SA_REP',   9000,   0.35,   146,   80); --59
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(159,   'Lindsey',   'Smith',   'LSMITH',   '011.44.1345.729268',   TO_DATE('2005/03/10','YY/MM/DD'),   'SA_REP',   8000,   0.3,   146,   80); --60
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(160,   'Louise',   'Doran',   'LDORAN',   '011.44.1345.629268',   TO_DATE('2005/12/15','YY/MM/DD'),   'SA_REP',   7500,   0.3,   146,   80); --61
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(161,   'Sarath',   'Sewall',   'SSEWALL',   '011.44.1345.529268',   TO_DATE('2006/11/03','YY/MM/DD'),   'SA_REP',   7000,   0.25,   146,   80); --62
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(162,   'Clara',   'Vishney',   'CVISHNEY',   '011.44.1346.129268',   TO_DATE('2005/11/11','YY/MM/DD'),   'SA_REP',   10500,   0.25,   147,   80); --63
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(163,   'Danielle',   'Greene',   'DGREENE',   '011.44.1346.229268',   TO_DATE('2007/03/19','YY/MM/DD'),   'SA_REP',   9500,   0.15,   147,   80); --64
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(164, 'Mattea',   'Marvins',      'MMARVINS',   '011.44.1346.329268',   TO_DATE('2008/01/24', 'YY/MM/DD'),   'SA_REP',       7200,   0.1,   147,  80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(165, 'David',   'Lee',      'DLEE',           '011.44.1346.529268',   TO_DATE('2008/02/23', 'YY/MM/DD'),   'SA_REP',       6800,   0.1,   147, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(166, 'Sundar',   'Ande',      'SANDE',          '011.44.1346.629268',   TO_DATE('2008/03/24', 'YY/MM/DD'),   'SA_REP',       6400,   0.1,   147, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(167, 'Amit',   'Banda',   'ABANDA',         '011.44.1346.729268',   TO_DATE('2008/04/21', 'YY/MM/DD'),   'SA_REP',       6200,   0.1,   147, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(168, 'Lisa',   'Ozer',   'LOZER',           '011.44.1343.929268',   TO_DATE('2005/03/11', 'YY/MM/DD'),   'SA_REP',       11500,   0.25,   148, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(169, 'Harrison', 'Bloom',   'HBLOOM',        '011.44.1343.829268',   TO_DATE('2006/03/23', 'YY/MM/DD'),   'SA_REP',       10000,    0.2,   148, 80); 
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(170, 'Tayler', 'Fox',       'TFOX',           '011.44.1343.729268',   TO_DATE('2006/01/24', 'YY/MM/DD'),   'SA_REP',       9600,    0.2,   148, 80); 
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(171, 'William', 'Smith',   'WSMITH',          '011.44.1343.629268',   TO_DATE('2007/02/23', 'YY/MM/DD'),   'SA_REP',       7400,    0.15,   148, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(172, 'Elizabeth', 'Bates',   'EBATES',        '011.44.1343.529268',   TO_DATE('2007/03/24', 'YY/MM/DD'),   'SA_REP',       7300,    0.15,   148, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(173, 'Sundita', 'Kumar',   'SKUMAR',          '011.44.1343.329268',   TO_DATE('2008/04/21', 'YY/MM/DD'),   'SA_REP',       6100,    0.1,   148, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(174, 'Ellen', 'Abel',   'EABEL',              '011.44.1644.429267',   TO_DATE('2004/05/11', 'YY/MM/DD'),   'SA_REP',       11000,    0.3,   149, 80);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(175, 'Alyssa', 'Hutton',   'AHUTTON',         '011.44.1644.429266',   TO_DATE('2005/03/19', 'YY/MM/DD'),   'SA_REP',       8800,    0.25,   149, 80);        
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(176, 'Jonathon', 'Taylor',   'JTAYLOR',       '011.44.1644.429265',   TO_DATE('2006/03/24', 'YY/MM/DD'),   'SA_REP',       8600,    0.2,   149, 80);  
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(177, 'Jack', 'Livingston',   'JLIVINGS',       '011.44.1644.429264',TO_DATE('2006/04/23', 'YY/MM/DD'),   'SA_REP',       8400,    0.2,   149, 80);  
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(178, 'Kimberely', 'Grant',   'KGRANT',       '011.44.1644.429263',TO_DATE('2007/05/24', 'YY/MM/DD'),   'SA_REP',       7000,    0.15,   149, NULL);  
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(179, 'Charles', 'Johnson',   'CJOHNSON',       '011.44.1644.429262',TO_DATE('2008/01/04', 'YY/MM/DD'),   'SA_REP',       6200,    0.1,   149, 80);    
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --81
VALUES(180, 'Winston',       'Taylor',       'WTAYLOR',             '650.507.9876',   TO_DATE('2006/01/24', 'YY/MM/DD'),   'SH_CLERK',       3200,   NULL,   120, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --82
VALUES(181, 'Jean',       'Fleaur',       'JFLEAUR',             '650.507.9877',   TO_DATE('2006/02/23', 'YY/MM/DD'),   'SH_CLERK',       3100,   NULL,   120, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --83
VALUES(182, 'Martha',       'Sullivan',       'MSULLIVA',             '650.507.9878',   TO_DATE('2007/06/21', 'YY/MM/DD'),   'SH_CLERK',       2500,   NULL,   120, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --84
VALUES(183, 'Girard',       'Geoni',       'GGEONI',             '6650.507.9879',   TO_DATE('2008/02/03', 'YY/MM/DD'),   'SH_CLERK',       2800,   NULL,   120, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --85
VALUES(184, 'Nandita',       'Sarchand',       'NSARCHAN',             '650.509.1876',   TO_DATE('2004/01/27', 'YY/MM/DD'),   'SH_CLERK',       4200,   NULL,   121, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --86
VALUES(185, 'Alexis',       'Bull',       'ABULL',             '650.509.2876',   TO_DATE('2005/02/20', 'YY/MM/DD'),   'SH_CLERK',       4100,   NULL,   121, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --87
VALUES(186, 'Julia',       'Dellinger',       'JDELLING',             '650.509.3876',   TO_DATE('2006/06/24', 'YY/MM/DD'),   'SH_CLERK',       3400,   NULL,   121, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --88
VALUES(187, 'Anthony',       'Cabrio',       'ACABRIO',             '650.509.4876',   TO_DATE('2007/02/07', 'YY/MM/DD'),   'SH_CLERK',       3000,   NULL,   121, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --89
VALUES(188, 'Kelly',       'Chung',       'KCHUNG',             '650.505.1876',   TO_DATE('2005/06/14', 'YY/MM/DD'),   'SH_CLERK',       3800,   NULL,   122, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --90
VALUES(189, 'Jennifer',       'Dilly',       'JDILLY',             '650.505.2876',   TO_DATE('2005/08/13', 'YY/MM/DD'),   'SH_CLERK',       3600,   NULL,   122, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --91
VALUES(190, 'Timothy',       'Gates',       'TGATES',             '650.505.3876',   TO_DATE('2006/07/11', 'YY/MM/DD'),   'SH_CLERK',       2900   ,   NULL,   122, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --92
VALUES(191, 'Randall',       'Perkins',       'RPERKINS',             '650.505.4876',   TO_DATE('2007/12/19', 'YY/MM/DD'),   'SH_CLERK',       2500,   NULL,   122, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) --93
VALUES(192, 'Sarah',       'Bell',       'SBELL',             '650.501.1876',   TO_DATE('2004/02/04', 'YY/MM/DD'),   'SH_CLERK',       4000,   NULL,   123, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(193, 'Britney',   'Everett',       'BEVERETT',  '650.501.2876',   TO_DATE('2005/03/03', 'YY/MM/DD'),   'ST_CLERK',       3900,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(194, 'Samuel',   'McCain',       'SMCCAIN',  '650.501.3876',   TO_DATE('2006/07/01', 'YY/MM/DD'),   'ST_CLERK',       3200,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(195, 'Vance',   'Jones',       'VJONES',  '650.501.4876',   TO_DATE('2007/03/17', 'YY/MM/DD'),   'ST_CLERK',       2800,   NULL,   123,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(196, 'Alana',   'Walsh',       'AWALSH',  '650.507.9811',   TO_DATE('2006/04/24', 'YY/MM/DD'),   'ST_CLERK',       3100,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(197, 'Kevin',   'Feeney',       'KFEENEY',  '650.507.9822',   TO_DATE('2006/05/23', 'YY/MM/DD'),   'ST_CLERK',       3000,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID)
VALUES(198, 'Donald',   'OConnell',       'DOCONNEL',  '650.507.9833',   TO_DATE('2007/06/21', 'YY/MM/DD'),   'ST_CLERK',       2600,   NULL,   124,  50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(199, 'Douglas', 'Grant', 'DGRANT', '650.507.9844', TO_DATE('2008/01/13', 'YYYY-MM-DD'), 'SH_CLERK', 2600, NULL, 124, 50);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(200, 'Jennifer', 'Whalen', 'JWHALEN', '515.123.4444', TO_DATE('2003/09/17', 'YYYY-MM-DD'), 'AD_ASST', 4400, NULL, 101, 10);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(201, 'Michael', 'Hartstein', 'MHARTSTE', '515.123.5555', TO_DATE('2004/02/17', 'YYYY-MM-DD'), 'MK_MAN', 13000, NULL, 100, 20);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(202, 'Pat', 'Fay', 'PFAY', '603.123.6666', TO_DATE('2005/08/17', 'YYYY-MM-DD'), 'MK_REP', 6000, NULL, 201, 20);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(203, 'Susan', 'Mavris', 'SMAVRIS', '515.123.7777', TO_DATE('2002/06/07', 'YYYY-MM-DD'), 'HR_REP', 6500, NULL, 101, 40);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(204, 'Hermann', 'Baer', 'HBAER', '515.123.8888', TO_DATE('2002/06/07', 'YYYY-MM-DD'), 'PR_REP', 10000, NULL, 101, 70);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(205, 'Shelley', 'Higgins', 'SHIGGINS', '515.123.8080', TO_DATE('2002/06/07', 'YYYY-MM-DD'), 'AC_MGR', 12008, NULL, 101, 110);
INSERT INTO EMPLOYEES01(EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) 
VALUES(206, 'William', 'Gietz', 'WGIETZ', '515.123.8181', TO_DATE('2002/06/07', 'YYYY-MM-DD'), 'AC_ACCOUNT', 8300, NULL, 205, 110);
--==>> 1 행 이(가) 삽입되었습니다. * 107

--확인
SELECT *
FROM EMPLOYEES01;


--JOB_HISTORY01 데이터
--INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) VALUES();

INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(102, TO_DATE('2001/01/13','YY/MM/DD'),TO_DATE('2006/07/24','YY/MM/DD'), 'IT_PROG', 60);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(101, TO_DATE('1997/09/13','YY/MM/DD'),TO_DATE('2001/10/27','YY/MM/DD'), 'AC_ACCOUNT', 110);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(101, TO_DATE('2001/10/28','YY/MM/DD'),TO_DATE('2005/03/15','YY/MM/DD'), 'AC_MGR', 110);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(201, TO_DATE('2004/02/17','YY/MM/DD'),TO_DATE('2007/12/19','YY/MM/DD'), 'MK_REP', 20);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(114, TO_DATE('2006/03/24','YY/MM/DD'),TO_DATE('2007/12/31','YY/MM/DD'), 'ST_CLERK', 50);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(122, TO_DATE('2007/01/01','YY/MM/DD'),TO_DATE('2007/12/31','YY/MM/DD'), 'ST_CLERK', 50);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(200, TO_DATE('1995/09/17','YY/MM/DD'),TO_DATE('2001/06/17','YY/MM/DD'), 'AD_ASST', 90);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(176, TO_DATE('2006/03/24','YY/MM/DD'),TO_DATE('2006-12-31','YY/MM/DD'), 'SA_REP', 80);                   
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(176, TO_DATE('2007/01/01','YY/MM/DD'),TO_DATE('2007/12/31','YY/MM/DD'), 'SA_MAN', 80);
INSERT INTO JOB_HISTORY01(EMPLOYEE_ID, START_DATE, END_DATE, JOB_ID, DEPARTMENT_ID) 
VALUES(200, TO_DATE('2002/07/01','YY/MM/DD'),TO_DATE('2006/12/31','YY/MM/DD'), 'AC_ACCOUNT', 90);
--==>> 1 행 이(가) 삽입되었습니다. * 10

--확인
SELECT *
FROM JOB_HISTORY01;




=================================================
-- (제거했던..) FOREIGN KEY 추가 지정
=================================================

-- COUNTRIES01 테이블 FK 제약조건 지정
ALTER TABLE COUNTRIES01
ADD CONSTRAINT COUNTR01_REG_FK  FOREIGN KEY((REGION_ID))
               REFERENCES REGIONS01(REGION_ID) ;

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='COUNTRIES01';


-- LOCATIONS01 테이블 FK 제약조건 지정
ALTER TABLE LOCATIONS01
ADD CONSTRAINT LOC01_C_ID_FK FOREIGN KEY(COUNTRY_ID)
               REFERENCES COUNTRIES01(COUNTRY_ID) ;
               
-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='LOCATIONS01';
               

-- DEPARTMENTS01 테이블 FK 제약조건 지정
ALTER TABLE DEPARTMENTS01
ADD CONSTRAINT DEPT01_LOC_FK FOREIGN KEY(LOCATION_ID)
               REFERENCES LOCATIONS01(LOCATION_ID) ;
       
ALTER TABLE DEPARTMENTS01
ADD CONSTRAINT DEPT01_MGR_FK FOREIGN KEY(MANAGER_ID)
               REFERENCES EMPLOYEES01(EMPLOYEE_ID);
               
-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='DEPARTMENTS01';


-- EMPLOYEES01 테이블 FK 제약조건 지정
ALTER TABLE EMPLOYEES01
ADD (CONSTRAINT EMP01_DEPT_FK FOREIGN KEY(DEPARTMENT_ID)
                REFERENCES DEPARTMENTS01(DEPARTMENT_ID)
   , CONSTRAINT EMP01_JOB_FK FOREIGN KEY(JOB_ID)
                REFERENCES JOBS01(JOB_ID)
   , CONSTRAINT EMP01_MANAGER_FK FOREIGN KEY(MANAGER_ID)
                REFERENCES EMPLOYEES01(EMPLOYEE_ID) );

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='EMPLOYEES01';


-- JOB_HISTORY01 테이블 FK 제약조건 지정
ALTER TABLE JOB_HISTORY01
ADD (CONSTRAINT JHIST01_JOB_FK FOREIGN KEY(JOB_ID)
                REFERENCES JOBS01(JOB_ID)
   , CONSTRAINT JHIST01_EMP_FK FOREIGN KEY(EMPLOYEE_ID)
                REFERENCES EMPLOYEES01(EMPLOYEE_ID)
   , CONSTRAINT JHIST01_DEPT_FK FOREIGN KEY(DEPARTMENT_ID)
                REFERENCES DEPARTMENTS01(DEPARTMENT_ID) );

-- 확인
SELECT *
FROM VIEW_CONSTCHECK
WHERE TABLE_NAME='JOB_HISTORY01';



























